// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// Run: protoc --go_out=. --go-grpc_out=. ../../proto/search/search.proto
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type SearchServiceServer interface {
	GetAvailability(context.Context, *GetAvailabilityRequest) (*GetAvailabilityResponse, error)
	GetFirstAvailable(context.Context, *GetFirstAvailableRequest) (*GetFirstAvailableResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) GetAvailability(context.Context, *GetAvailabilityRequest) (*GetAvailabilityResponse, error) {
	return nil, nil
}
func (UnimplementedSearchServiceServer) GetFirstAvailable(context.Context, *GetFirstAvailableRequest) (*GetFirstAvailableResponse, error) {
	return nil, nil
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	// TODO: replace with generated registration
}

type GetAvailabilityRequest struct {
	Floor       int32
	VehicleType string
}

type SpotSummary struct {
	SpotId      string
	Floor       int32
	VehicleType string
	Status      string
}

type GetAvailabilityResponse struct {
	Floor          int32
	VehicleType    string
	TotalAvailable int32
	Spots          []*SpotSummary
}

type GetFirstAvailableRequest struct {
	VehicleType string
}

type GetFirstAvailableResponse struct {
	SpotId string
}
