// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type SearchServiceServer interface {
	GetAvailability(context.Context, *GetAvailabilityRequest) (*GetAvailabilityResponse, error)
	GetFirstAvailable(context.Context, *GetFirstAvailableRequest) (*GetFirstAvailableResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) GetAvailability(context.Context, *GetAvailabilityRequest) (*GetAvailabilityResponse, error) {
	return nil, nil
}
func (UnimplementedSearchServiceServer) GetFirstAvailable(context.Context, *GetFirstAvailableRequest) (*GetFirstAvailableResponse, error) {
	return nil, nil
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	sd := grpc.ServiceDesc{
		ServiceName: "search.SearchService",
		HandlerType: (*SearchServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{MethodName: "GetAvailability", Handler: _SearchService_GetAvailability_Handler},
			{MethodName: "GetFirstAvailable", Handler: _SearchService_GetFirstAvailable_Handler},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "search.proto",
	}
	s.RegisterService(&sd, srv)
}

func _SearchService_GetAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(SearchServiceServer).GetAvailability(ctx, in)
}

func _SearchService_GetFirstAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFirstAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(SearchServiceServer).GetFirstAvailable(ctx, in)
}

type GetAvailabilityRequest struct {
	Floor       int32  `json:"floor"`
	VehicleType string `json:"vehicle_type"`
}

type SpotSummary struct {
	SpotId      string `json:"spot_id"`
	Floor       int32  `json:"floor"`
	VehicleType string `json:"vehicle_type"`
	Status      string `json:"status"`
}

type GetAvailabilityResponse struct {
	Floor          int32          `json:"floor"`
	VehicleType    string         `json:"vehicle_type"`
	TotalAvailable int32          `json:"total_available"`
	Spots          []*SpotSummary `json:"spots"`
}

type GetFirstAvailableRequest struct {
	VehicleType string `json:"vehicle_type"`
}

type GetFirstAvailableResponse struct {
	SpotId string `json:"spot_id"`
}
