apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: parkir-pintar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        traffic.sidecar.istio.io/excludeInboundPorts: "8080"
    spec:
      containers:
        - name: billing-service
          image: parkirpintar/billing-service:latest
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 8080
              name: http-rest
          env:
            - name: OTEL_SERVICE_NAME
              value: "billing-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=parkir-pintar"
          envFrom:
            - configMapRef:
                name: parkirpintar-config
            - secretRef:
                name: billing-db-secret
            - secretRef:
                name: rabbitmq-secret
            - secretRef:
                name: redis-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: parkir-pintar
spec:
  selector:
    app: billing-service
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
    - appProtocol: http
      port: 8080
      targetPort: 8080
      name: http-rest
  type: ClusterIP
