apiVersion: v1
kind: ConfigMap
metadata:
  name: parkirpintar-config
  namespace: parkir-pintar
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  GRPC_PORT: "50051"
  PAYMENT_ADDR: "payment-service.parkir-pintar.svc.cluster.local:50051"
  BILLING_ADDR: "billing-service.parkir-pintar.svc.cluster.local:50051"
  SEARCH_ADDR: "search-service.parkir-pintar.svc.cluster.local:50051"
  RESERVATION_ADDR: "reservation-service.parkir-pintar.svc.cluster.local:50051"
  PRESENCE_ADDR: "presence-service.parkir-pintar.svc.cluster.local:50051"
  SETTLEMENT_URL: "http://settlement-stub.parkir-pintar.svc.cluster.local:8080"
  NOTIF_PROVIDER_URL: "http://settlement-stub.parkir-pintar.svc.cluster.local:8080/notify"
---
apiVersion: v1
kind: Secret
metadata:
  name: reservation-db-secret
  namespace: parkir-pintar
type: Opaque
stringData:
  DB_HOST: "<RDS_RESERVATION_HOST>"
  DB_PORT: "5432"
  DB_NAME: "reservation"
  DB_USER: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"
  DB_SSLMODE: "require"
  DB_REPLICA_HOST: "<RDS_RESERVATION_REPLICA_HOST>"
  DATABASE_URL: "postgres://<DB_USERNAME>:<DB_PASSWORD>@<RDS_RESERVATION_HOST>:5432/reservation?sslmode=require"
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secret
  namespace: parkir-pintar
type: Opaque
stringData:
  DB_HOST: "<RDS_BILLING_HOST>"
  DB_PORT: "5432"
  DB_NAME: "billing"
  DB_USER: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"
  DB_SSLMODE: "require"
  DATABASE_URL: "postgres://<DB_USERNAME>:<DB_PASSWORD>@<RDS_BILLING_HOST>:5432/billing?sslmode=require"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: parkir-pintar
type: Opaque
stringData:
  DB_HOST: "<RDS_PAYMENT_HOST>"
  DB_PORT: "5432"
  DB_NAME: "payment"
  DB_USER: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"
  DB_SSLMODE: "require"
  DATABASE_URL: "postgres://<DB_USERNAME>:<DB_PASSWORD>@<RDS_PAYMENT_HOST>:5432/payment?sslmode=require"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-db-secret
  namespace: parkir-pintar
type: Opaque
stringData:
  DB_HOST: "<RDS_ANALYTICS_HOST>"
  DB_PORT: "5432"
  DB_NAME: "analytics"
  DB_USER: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"
  DB_SSLMODE: "require"
  DATABASE_URL: "postgres://<DB_USERNAME>:<DB_PASSWORD>@<RDS_ANALYTICS_HOST>:5432/analytics?sslmode=require"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: parkir-pintar
type: Opaque
stringData:
  REDIS_HOST: "<ELASTICACHE_HOST>"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: parkir-pintar
type: Opaque
stringData:
  RABBITMQ_URL: "amqps://<MQ_USERNAME>:<MQ_PASSWORD>@<AMAZON_MQ_HOST>:5671"
