apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: parkir-pintar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
        version: v1
    spec:
      containers:
        - name: gateway
          image: parkirpintar/gateway-service:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: HTTP_ADDR
              value: ":8080"
          envFrom:
            - configMapRef:
                name: parkirpintar-config
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: parkir-pintar
spec:
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
