apiVersion: apps/v1
kind: Deployment
metadata:
  name: presence-service
  namespace: parkir-pintar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: presence-service
  template:
    metadata:
      labels:
        app: presence-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      containers:
        - name: presence-service
          image: parkirpintar/presence-service:latest
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: parkirpintar-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: presence-service
  namespace: parkir-pintar
spec:
  selector:
    app: presence-service
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
    - appProtocol: http
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
