apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: parkir-pintar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      containers:
        - name: reservation-service
          image: parkirpintar/reservation-service:latest
          ports:
            - containerPort: 50051
              name: grpc
          envFrom:
            - configMapRef:
                name: parkirpintar-config
            - secretRef:
                name: reservation-db-secret
            - secretRef:
                name: redis-secret
            - secretRef:
                name: rabbitmq-secret
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: parkir-pintar
spec:
  selector:
    app: reservation-service
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
  type: ClusterIP
