apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: parkir-pintar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      containers:
        - name: user-service
          image: parkirpintar/user-service:latest
          ports:
            - containerPort: 50051
              name: grpc
          envFrom:
            - configMapRef:
                name: parkirpintar-config
            - secretRef:
                name: user-db-secret
            - secretRef:
                name: redis-secret
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: parkir-pintar
spec:
  selector:
    app: user-service
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
  type: ClusterIP
