sonar.projectKey=ParkirPintar_parkir-pintar-backend
sonar.organization=parkirpintar

sonar.sources=services
sonar.tests=services
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/*_test.go,**/proto/**/*.go,**/migrations/**

sonar.go.coverage.reportPaths=services/analytics/coverage.out,services/billing/coverage.out,services/notification/coverage.out,services/payment/coverage.out,services/presence/coverage.out,services/reservation/coverage.out,services/search/coverage.out,services/user/coverage.out

sonar.sourceEncoding=UTF-8
