// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type PaymentServiceServer interface {
	CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error)
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*PaymentResponse, error)
	RetryPayment(context.Context, *RetryPaymentRequest) (*PaymentResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error) {
	return nil, nil
}
func (UnimplementedPaymentServiceServer) GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*PaymentResponse, error) {
	return nil, nil
}
func (UnimplementedPaymentServiceServer) RetryPayment(context.Context, *RetryPaymentRequest) (*PaymentResponse, error) {
	return nil, nil
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	sd := grpc.ServiceDesc{
		ServiceName: "payment.PaymentService",
		HandlerType: (*PaymentServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{MethodName: "CreatePayment", Handler: paymentServiceCreatePaymentHandler},
			{MethodName: "GetPaymentStatus", Handler: paymentServiceGetPaymentStatusHandler},
			{MethodName: "RetryPayment", Handler: paymentServiceRetryPaymentHandler},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "payment.proto",
	}
	s.RegisterService(&sd, srv)
}

func paymentServiceCreatePaymentHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(PaymentServiceServer).CreatePayment(ctx, in)
}

func paymentServiceGetPaymentStatusHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(PaymentServiceServer).GetPaymentStatus(ctx, in)
}

func paymentServiceRetryPaymentHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(PaymentServiceServer).RetryPayment(ctx, in)
}

type CreatePaymentRequest struct {
	InvoiceId      string `json:"invoice_id"`
	Amount         int64  `json:"amount"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetPaymentStatusRequest struct {
	PaymentId string `json:"payment_id"`
}

type RetryPaymentRequest struct {
	PaymentId      string `json:"payment_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type PaymentResponse struct {
	PaymentId string `json:"payment_id"`
	InvoiceId string `json:"invoice_id"`
	Status    string `json:"status"`
	Amount    int64  `json:"amount"`
	Method    string `json:"method"`
	QrCode    string `json:"qr_code"`
	UpdatedAt string `json:"updated_at"`
}
