// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// Run: protoc --go_out=. --go-grpc_out=. ../../proto/payment/payment.proto
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type PaymentServiceServer interface {
	CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error)
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*PaymentResponse, error)
	RetryPayment(context.Context, *RetryPaymentRequest) (*PaymentResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*PaymentResponse, error) {
	return nil, nil
}
func (UnimplementedPaymentServiceServer) GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*PaymentResponse, error) {
	return nil, nil
}
func (UnimplementedPaymentServiceServer) RetryPayment(context.Context, *RetryPaymentRequest) (*PaymentResponse, error) {
	return nil, nil
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {}

type CreatePaymentRequest struct {
	InvoiceId      string
	Amount         int64
	IdempotencyKey string
}

type GetPaymentStatusRequest struct {
	PaymentId string
}

type RetryPaymentRequest struct {
	PaymentId      string
	IdempotencyKey string
}

type PaymentResponse struct {
	PaymentId string
	InvoiceId string
	Status    string
	Amount    int64
	Method    string
	QrCode    string
	UpdatedAt string
}
