// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type RegisterRequest struct {
	LicensePlate string `json:"license_plate"`
	VehicleType  string `json:"vehicle_type"`
	Password     string `json:"password"`
	Name         string `json:"name"`
	PhoneNumber  string `json:"phone_number"`
}

type LoginRequest struct {
	LicensePlate string `json:"license_plate"`
	VehicleType  string `json:"vehicle_type"`
	Password     string `json:"password"`
}

type LoginResponse struct {
	UserId       string `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LogoutRequest struct {
	AccessToken string `json:"access_token"`
}

type LogoutResponse struct {
	Success bool `json:"success"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type GetProfileRequest struct {
	UserId string `json:"user_id"`
}

type UpdateProfileRequest struct {
	UserId      string `json:"user_id"`
	Name        string `json:"name"`
	PhoneNumber string `json:"phone_number"`
}

type UserResponse struct {
	UserId       string `json:"user_id"`
	LicensePlate string `json:"license_plate"`
	VehicleType  string `json:"vehicle_type"`
	Name         string `json:"name"`
	PhoneNumber  string `json:"phone_number"`
}

type UserServiceServer interface {
	Register(context.Context, *RegisterRequest) (*UserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*LoginResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*UserResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UserResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) Register(context.Context, *RegisterRequest) (*UserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*LoginResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) GetProfile(context.Context, *GetProfileRequest) (*UserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	sd := grpc.ServiceDesc{
		ServiceName: "proto.UserService",
		HandlerType: (*UserServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{MethodName: "Register", Handler: _UserService_Register_Handler},
			{MethodName: "Login", Handler: _UserService_Login_Handler},
			{MethodName: "Logout", Handler: _UserService_Logout_Handler},
			{MethodName: "RefreshToken", Handler: _UserService_RefreshToken_Handler},
			{MethodName: "GetProfile", Handler: _UserService_GetProfile_Handler},
			{MethodName: "UpdateProfile", Handler: _UserService_UpdateProfile_Handler},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "user.proto",
	}
	s.RegisterService(&sd, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServiceServer).Register(ctx, in)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServiceServer).Login(ctx, in)
}

func _UserService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServiceServer).Logout(ctx, in)
}

func _UserService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServiceServer).RefreshToken(ctx, in)
}

func _UserService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServiceServer).GetProfile(ctx, in)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServiceServer).UpdateProfile(ctx, in)
}
