// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Stub — replace with generated code from proto/user/user.proto

package proto

import "google.golang.org/grpc"

type RegisterRequest struct {
	LicensePlate string
	VehicleType  string
	Password     string
	Name         string
	PhoneNumber  string
}

type LoginRequest struct {
	LicensePlate string
	VehicleType  string
	Password     string
}

type LoginResponse struct {
	UserId       string
	AccessToken  string
	RefreshToken string
}

type LogoutRequest struct {
	AccessToken string
}

type LogoutResponse struct {
	Success bool
}

type RefreshTokenRequest struct {
	RefreshToken string
}

type GetProfileRequest struct{ UserId string }

type UpdateProfileRequest struct {
	UserId      string
	Name        string
	PhoneNumber string
}

type UserResponse struct {
	UserId       string
	LicensePlate string
	VehicleType  string
	Name         string
	PhoneNumber  string
}

type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) Register(_ interface{}, _ *RegisterRequest) (*UserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) Login(_ interface{}, _ *LoginRequest) (*LoginResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) Logout(_ interface{}, _ *LogoutRequest) (*LogoutResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) RefreshToken(_ interface{}, _ *RefreshTokenRequest) (*LoginResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) GetProfile(_ interface{}, _ *GetProfileRequest) (*UserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) UpdateProfile(_ interface{}, _ *UpdateProfileRequest) (*UserResponse, error) {
	return nil, nil
}

func RegisterUserServiceServer(s *grpc.Server, srv interface{}) {
	// TODO: replace with generated registration
}

var _ grpc.ServiceRegistrar = nil // ensure grpc import used
