// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type BillingServiceServer interface {
	ChargeBookingFee(context.Context, *ChargeBookingFeeRequest) (*BillingResponse, error)
	StartBillingSession(context.Context, *StartBillingSessionRequest) (*BillingResponse, error)
	ApplyPenalty(context.Context, *ApplyPenaltyRequest) (*BillingResponse, error)
	Checkout(context.Context, *CheckoutRequest) (*InvoiceResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) ChargeBookingFee(context.Context, *ChargeBookingFeeRequest) (*BillingResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) StartBillingSession(context.Context, *StartBillingSessionRequest) (*BillingResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) ApplyPenalty(context.Context, *ApplyPenaltyRequest) (*BillingResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) Checkout(context.Context, *CheckoutRequest) (*InvoiceResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}

func RegisterBillingServiceServer(s *grpc.Server, srv BillingServiceServer) {
	sd := grpc.ServiceDesc{
		ServiceName: "billing.BillingService",
		HandlerType: (*BillingServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{MethodName: "ChargeBookingFee", Handler: billingServiceChargeBookingFeeHandler},
			{MethodName: "StartBillingSession", Handler: billingServiceStartBillingSessionHandler},
			{MethodName: "ApplyPenalty", Handler: billingServiceApplyPenaltyHandler},
			{MethodName: "Checkout", Handler: billingServiceCheckoutHandler},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "billing.proto",
	}
	s.RegisterService(&sd, srv)
}

func billingServiceChargeBookingFeeHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeBookingFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(BillingServiceServer).ChargeBookingFee(ctx, in)
}

func billingServiceStartBillingSessionHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBillingSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(BillingServiceServer).StartBillingSession(ctx, in)
}

func billingServiceApplyPenaltyHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPenaltyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(BillingServiceServer).ApplyPenalty(ctx, in)
}

func billingServiceCheckoutHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(BillingServiceServer).Checkout(ctx, in)
}

type ChargeBookingFeeRequest struct {
	ReservationId string `json:"reservation_id"`
	Amount        int64  `json:"amount"`
}

type StartBillingSessionRequest struct {
	ReservationId string `json:"reservation_id"`
	CheckinAt     string `json:"checkin_at"`
}

type ApplyPenaltyRequest struct {
	ReservationId string `json:"reservation_id"`
	Reason        string `json:"reason"`
	Amount        int64  `json:"amount"`
}

type BillingResponse struct {
	BillingId string `json:"billing_id"`
	Status    string `json:"status"`
}

type CheckoutRequest struct {
	ReservationId  string `json:"reservation_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type InvoiceResponse struct {
	InvoiceId       string `json:"invoice_id"`
	ReservationId   string `json:"reservation_id"`
	BookingFee      int64  `json:"booking_fee"`
	HourlyFee       int64  `json:"hourly_fee"`
	OvernightFee    int64  `json:"overnight_fee"`
	Penalty         int64  `json:"penalty"`
	NoshowFee       int64  `json:"noshow_fee"`
	CancellationFee int64  `json:"cancellation_fee"`
	Total           int64  `json:"total"`
	Status          string `json:"status"`
	QrCode          string `json:"qr_code"`
	PaymentId       string `json:"payment_id"`
}
