// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// Run: protoc --go_out=. --go-grpc_out=. ../../proto/billing/billing.proto
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type BillingServiceServer interface {
	ChargeBookingFee(context.Context, *ChargeBookingFeeRequest) (*BillingResponse, error)
	StartBillingSession(context.Context, *StartBillingSessionRequest) (*BillingResponse, error)
	ApplyPenalty(context.Context, *ApplyPenaltyRequest) (*BillingResponse, error)
	Checkout(context.Context, *CheckoutRequest) (*InvoiceResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) ChargeBookingFee(context.Context, *ChargeBookingFeeRequest) (*BillingResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) StartBillingSession(context.Context, *StartBillingSessionRequest) (*BillingResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) ApplyPenalty(context.Context, *ApplyPenaltyRequest) (*BillingResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) Checkout(context.Context, *CheckoutRequest) (*InvoiceResponse, error) {
	return nil, nil
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}

func RegisterBillingServiceServer(s *grpc.Server, srv BillingServiceServer) {}

type ChargeBookingFeeRequest struct {
	ReservationId string
	Amount        int64
}

type StartBillingSessionRequest struct {
	ReservationId string
	CheckinAt     string
}

type ApplyPenaltyRequest struct {
	ReservationId string
	Reason        string
	Amount        int64
}

type BillingResponse struct {
	BillingId string
	Status    string
}

type CheckoutRequest struct {
	ReservationId  string
	IdempotencyKey string
}

type InvoiceResponse struct {
	InvoiceId       string
	ReservationId   string
	BookingFee      int64
	HourlyFee       int64
	OvernightFee    int64
	Penalty         int64
	NoshowFee       int64
	CancellationFee int64
	Total           int64
	Status          string
	QrCode          string
	PaymentId       string
}
