// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// Run: protoc --go_out=. --go-grpc_out=. ../../proto/reservation/reservation.proto
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type ReservationServiceServer interface {
	CreateReservation(context.Context, *CreateReservationRequest) (*ReservationResponse, error)
	HoldSpot(context.Context, *HoldSpotRequest) (*HoldSpotResponse, error)
	CancelReservation(context.Context, *CancelReservationRequest) (*CancelReservationResponse, error)
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	GetReservation(context.Context, *GetReservationRequest) (*ReservationResponse, error)
	mustEmbedUnimplementedReservationServiceServer()
}

type UnimplementedReservationServiceServer struct{}

func (UnimplementedReservationServiceServer) CreateReservation(context.Context, *CreateReservationRequest) (*ReservationResponse, error) {
	return nil, nil
}
func (UnimplementedReservationServiceServer) HoldSpot(context.Context, *HoldSpotRequest) (*HoldSpotResponse, error) {
	return nil, nil
}
func (UnimplementedReservationServiceServer) CancelReservation(context.Context, *CancelReservationRequest) (*CancelReservationResponse, error) {
	return nil, nil
}
func (UnimplementedReservationServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, nil
}
func (UnimplementedReservationServiceServer) GetReservation(context.Context, *GetReservationRequest) (*ReservationResponse, error) {
	return nil, nil
}
func (UnimplementedReservationServiceServer) mustEmbedUnimplementedReservationServiceServer() {}

func RegisterReservationServiceServer(s *grpc.Server, srv ReservationServiceServer) {}

type CreateReservationRequest struct {
	Mode           string
	VehicleType    string
	SpotId         string
	IdempotencyKey string
}

type ReservationResponse struct {
	ReservationId string
	SpotId        string
	Mode          string
	Status        string
	BookingFee    int64
	ConfirmedAt   string
	ExpiresAt     string
}

type HoldSpotRequest struct {
	SpotId   string
	DriverId string
}

type HoldSpotResponse struct {
	SpotId    string
	HeldUntil string
}

type CancelReservationRequest struct {
	ReservationId string
}

type CancelReservationResponse struct {
	ReservationId   string
	Status          string
	CancellationFee int64
}

type CheckInRequest struct {
	ReservationId string
	ActualSpotId  string
}

type CheckInResponse struct {
	ReservationId  string
	Status         string
	CheckinAt      string
	WrongSpot      bool
	PenaltyApplied int64
}

type GetReservationRequest struct {
	ReservationId string
}
