// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// Run: protoc --go_out=. --go-grpc_out=. ../../proto/presence/presence.proto
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type PresenceServiceServer interface {
	UpdateLocation(context.Context, *LocationUpdate) (*PresenceEvent, error)
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	CheckOut(context.Context, *CheckOutRequest) (*CheckOutResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) UpdateLocation(context.Context, *LocationUpdate) (*PresenceEvent, error) {
	return nil, nil
}
func (UnimplementedPresenceServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, nil
}
func (UnimplementedPresenceServiceServer) CheckOut(context.Context, *CheckOutRequest) (*CheckOutResponse, error) {
	return nil, nil
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}

func RegisterPresenceServiceServer(s *grpc.Server, srv PresenceServiceServer) {
	sd := grpc.ServiceDesc{
		ServiceName: "presence.PresenceService",
		HandlerType: (*PresenceServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{MethodName: "UpdateLocation", Handler: presenceServiceUpdateLocationHandler},
			{MethodName: "CheckIn", Handler: presenceServiceCheckInHandler},
			{MethodName: "CheckOut", Handler: presenceServiceCheckOutHandler},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "presence.proto",
	}
	s.RegisterService(&sd, srv)
}

func presenceServiceUpdateLocationHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(PresenceServiceServer).UpdateLocation(ctx, in)
}

func presenceServiceCheckInHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(PresenceServiceServer).CheckIn(ctx, in)
}

func presenceServiceCheckOutHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, _ grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(PresenceServiceServer).CheckOut(ctx, in)
}

// --- Message types ---

type LocationUpdate struct {
	ReservationId string  `json:"reservation_id"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	Timestamp     string  `json:"timestamp"`
}

type PresenceEvent struct {
	ReservationId string `json:"reservation_id"`
	Event         string `json:"event"`
	SpotId        string `json:"spot_id"`
	Timestamp     string `json:"timestamp"`
}

type CheckInRequest struct {
	ReservationId string `json:"reservation_id"`
	SpotId        string `json:"spot_id"`
}

type CheckInResponse struct {
	ReservationId string `json:"reservation_id"`
	Status        string `json:"status"`
	CheckinAt     string `json:"checkin_at"`
	WrongSpot     bool   `json:"wrong_spot"`
}

type CheckOutRequest struct {
	ReservationId string `json:"reservation_id"`
}

type CheckOutResponse struct {
	ReservationId string `json:"reservation_id"`
	Status        string `json:"status"`
}
