// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
package proto

import (
	"google.golang.org/grpc"
)

type PresenceServiceServer interface {
	StreamLocation(PresenceService_StreamLocationServer) error
	mustEmbedUnimplementedPresenceServiceServer()
}

type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) StreamLocation(PresenceService_StreamLocationServer) error {
	return nil
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}

func RegisterPresenceServiceServer(s *grpc.Server, srv PresenceServiceServer) {
	sd := grpc.ServiceDesc{
		ServiceName: "presence.PresenceService",
		HandlerType: (*PresenceServiceServer)(nil),
		Methods:     []grpc.MethodDesc{},
		Streams: []grpc.StreamDesc{
			{
				StreamName:    "StreamLocation",
				Handler:       presenceServiceStreamLocationHandler,
				ServerStreams:  true,
				ClientStreams:  true,
			},
		},
		Metadata: "presence.proto",
	}
	s.RegisterService(&sd, srv)
}

func presenceServiceStreamLocationHandler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PresenceServiceServer).StreamLocation(&presenceStreamLocationServer{stream})
}

type presenceStreamLocationServer struct {
	grpc.ServerStream
}

func (x *presenceStreamLocationServer) Send(m *PresenceEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *presenceStreamLocationServer) Recv() (*LocationUpdate, error) {
	m := new(LocationUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type PresenceService_StreamLocationServer interface {
	Send(*PresenceEvent) error
	Recv() (*LocationUpdate, error)
	grpc.ServerStream
}

type LocationUpdate struct {
	ReservationId string  `json:"reservation_id"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	Timestamp     string  `json:"timestamp"`
}

type PresenceEvent struct {
	ReservationId string `json:"reservation_id"`
	Event         string `json:"event"`
	SpotId        string `json:"spot_id"`
	Timestamp     string `json:"timestamp"`
}
