// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// Run: protoc --go_out=. --go-grpc_out=. ../../proto/presence/presence.proto
package proto

import (
	"google.golang.org/grpc"
)

type PresenceServiceServer interface {
	StreamLocation(PresenceService_StreamLocationServer) error
	mustEmbedUnimplementedPresenceServiceServer()
}

type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) StreamLocation(PresenceService_StreamLocationServer) error {
	return nil
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}

func RegisterPresenceServiceServer(s *grpc.Server, srv PresenceServiceServer) {}

type PresenceService_StreamLocationServer interface {
	Send(*PresenceEvent) error
	Recv() (*LocationUpdate, error)
	grpc.ServerStream
}

type LocationUpdate struct {
	ReservationId string
	Latitude      float64
	Longitude     float64
	Timestamp     string
}

type PresenceEvent struct {
	ReservationId string
	Event         string
	SpotId        string
	Timestamp     string
}
